# This is used by repo2docker. conda can install all the Jupyter dependencies.

name: jyve-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - beautysh
  - flake8
  - geckodriver
  - jupyterlab >=0.34,<0.35
  - nodejs >=8.9.3,<9
  - python >=3.6,<3.7
  - python-chromedriver-binary
  - robotframework-lint
  - robotframework-seleniumlibrary
  - selenium >=3.14, <3.15
  - wget
